# develop stage
FROM node:alpine as develop-stage
WORKDIR /app
COPY /app/package*.json .
RUN npm install
COPY . ./

# build stage
FROM develop-stage as build-stage
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

# production stage
FROM nginx:alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]